export function translate(word: string): string {
    const knowWords = {
        automaker: "Montadora",
        model: "Modelo",
        year_start: "Ano Modelo de",
        year_end: "Ano modelo até",
        engine: "Motor",
        complement: "Complemento",
        quantity_used: "Quantidade usada",
        size: "Tamanho",
        height: "Altura",
        width: "Largura",
        length: "Comprimento",
        lenth: "Comprimento", //em alguns lugares esta escrito incorretamente
        weight: "Peso",
        inner_diameter: "Diametro Interno",
        external_diameter: "Diametro externo",
        title: "Titulo",
        name: "Nome",
        type: "Tipo",
        position: "Posição",
        system: "Sistema",
        color: "Cor",
        material: "Material",
        obs: "Observação",
        group_id: "Id do Grupo",
        subgroup_id: "Id do Sub-Grupo",
        created_at: "Criado em",
        updated_at: "Atualizado em",
        fuel: "Combustível",
        chassi: "Chassi",
        year_fab: "Ano de fabricação",
        year_model: "Ano do modelo",
        quality: "Qualidade",
        price: "Preço",
        branch_type: "Seguimento",
        provider_description: "Descrição do Fornecedor",
        depth: "Espessura",
        provider_name: "Fornecedor",
        ncm: "NCM Código Fiscal",
        sku: "Código Fornecedor",
        eam: "EAM Código Barras",
        oem: "OEM Código Original",
        mpn: "MPN Código Marca",
        brand: "Marca do Produto",
        purchase_packaging: "Embalagem de Compra",
        quantity_package: "Embalagem de Venda",
        inactive: "Inativo",
        place: "Local do Produto",
        unity: "Unidade",
        cost_price: "Preço de Custo",
        sale_price: "Preço de Venda",
        description: "descrição",
        type_mlb: "Tipo MLB",
        variations_mlb: "Variações MLB",
        assignments_mlb: "Atribuições MLB",
        category_id_mlb: "ID Categoria MLB",
        measure: "Medida"

    }


    return knowWords[word] || `Não encontramos ${word}`
}